export const projects = [
  {
    title: "Home & Home",
    description: "A Real Estate Website with advanced property filtering.",
    image: "/images/1.png",
    tags: ["React", "Javascript", "Next.js", "Api"],
    source: "https://home-and-home.vercel.app/",
    visit: "https://github.com/Joshhortt/home_home",
    id: 0,
  },
  {
    title: "Restaurant PB",
    description:
      "IN DEVELOPMENT. Portuguese Fine Dining Restaurant Landing Page.",
    image: "/images/2.png",
    tags: ["React", "Javascript", "BEM Css", "Figma"],
    source: "https://restaurantpeterbrissos.netlify.app/",
    visit: "https://github.com/Joshhortt/restaurante-pt",
    id: 1,
  },
  // {
  //   title: "Amazon Data Crawler",
  //   description:
  //     "UPDATING: A ScraperAPI, for scraping Amazon's product details & search results data into JSON format.",
  //   image: "/images/3.png",
  //   tags: ["Javascript", "Json", "ScraperApi", "RapidApi"],
  //   source: "https://amazon-data-crawler.herokuapp.com/",
  //   staging: "https://rapidapi.com/joshhortt/api/amazon-data-crawler/",
  //   visit: "https://github.com/Joshhortt/amazon_data_crawler",
  //   id: 2,
  // },
  // {
  //   title: "Privatechat",
  //   description:
  //     "A Realtime Chat 'Messenger' Application with Facebook and Google login.",
  //   image: "/images/4.png",
  //   tags: ["React", "ChatEngine", "Javascript", "Firebase"],
  //   source: "https://privatechatmessenger.netlify.app/",
  //   visit: "https://github.com/Joshhortt/private-chat-messenger",
  //   id: 3,
  // },
  {
    title: "Phonix shop",
    description: "IN DEVELOPMENT. A Technology Ecommerce site.",
    image: "/images/5.PNG",
    tags: ["Sanity", "Stripe", "Next.js", "React"],
    source: "https://ecommerce-shop-f1na-qka25av2j-joshhortt.vercel.app/",
    staging: "https://ecommerce-shop-f1na-qka25av2j-joshhortt.vercel.app/",
    visit: "https://github.com/Joshhortt/ecommerce-shop",
    id: 2,
  },
  // {
  //   title: "Pretty Cash",
  //   description: "IN DEVELOPMENT. 2hand Ecommerce site.",
  //   image: "/images/6.PNG",
  //   tags: ["Css", "Stripe", "Javascript"],
  //   source: "",
  //   visit: "https://github.com/Joshhortt/pretty-cash",
  //   id: 5,
  // },
  {
    title: "CC Property Services",
    description: "A Vacation Rental Property Services Company Landing Page.",
    image: "/images/7.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://casacasa.pt",
    visit: "https://github.com/Joshhortt/casa-casa",
    id: 3,
  },
  {
    title: "Bitmatica",
    description: "A Hardware & Software E-commerce Website.",
    image: "/images/8.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://bitmatica.pt/",
    visit: "https://github.com/Joshhortt/bitmatica",
    id: 4,
  },
  {
    title: "Blue Door Lagos",
    description: "A Vacation Rental Booking Website.",
    image: "/images/9.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://bluedoorlagos.com/",
    visit: "https://github.com/Joshhortt/blue-door-lagos/",
    id: 5,
  },
  {
    title: "Lagos Bay View Flat",
    description: "A Vacation Rental Booking Website.",
    image: "/images/10.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://lagosbayviewflat.com/",
    visit: "https://github.com/Joshhortt/lagos-bay-view-flat/",
    id: 6,
  },
  {
    title: "Vinyl Flat",
    description: "A Vacation Rental Booking Website.",
    image: "/images/11.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://vinylflat.pt/",
    visit: "https://github.com/Joshhortt/vinyl-flat/",
    id: 7,
  },
  {
    title: "Casa Beatriz",
    description: "A Vacation Rental Booking Website.",
    image: "/images/12.PNG",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://casabeatriz.pt/",
    visit: "https://github.com/Joshhortt/casa-beatriz/",
    id: 8,
  },
  // {
  //   title: "Dev Match",
  //   description: "A Ruby on Rails CRUD Application.",
  //   image: "/images/13.PNG",
  //   tags: ["Ruby on Rails", "MySql", "Javascript"],
  //   source: "https://lit-river-74323.herokuapp.com/",
  //   visit: "https://github.com/Joshhortt/dev-match",
  //   id: 12,
  // },
  {
    title: "Designer Portfolio",
    description: "A Portfolio Landing Page for artists.",
    image: "/images/14.PNG",
    tags: ["Html", "Css", "Javascript"],
    source: "https://designer-portfolio-jade.vercel.app/",
    visit: "https://github.com/Joshhortt/designer-portfolio",
    id: 9,
  },
  {
    title: "De Flat",
    description: "A Vacation Rental Booking Website.",
    image: "/images/15.png",
    tags: ["Php", "MySql", "Javascript", "Cms"],
    source: "https://deflat.pt/",
    visit: "https://github.com/Joshhortt/de-flat",
    id: 10,
  },
  {
    title: "GymX",
    description: "A Gym Landing Page.",
    image: "/images/16.png",
    tags: ["Html", "Css", "Javascript"],
    source: "https://gym-x.vercel.app/",
    visit: "https://github.com/Joshhortt/gym-app",
    id: 11,
  },
  {
    title: ".trainers",
    description: "A trainers E-commerce shop.",
    image: "/images/17.png",
    tags: ["Html", "Css", "Javascript"],
    source: "https://trainers-shop.vercel.app/",
    visit: "https://github.com/Joshhortt/trainers-shop",
    id: 12,
  },
  {
    title: "The Power-Attic",
    description: "A Landing Page for Personal Trainers.",
    image: "/images/18.png",
    tags: ["Html", "Tailwind Css", "Javascript"],
    source: "https://power-attic.vercel.app/",
    visit: "https://github.com/Joshhortt/power-attic",
    id: 13,
  },
  {
    title: "JAHC",
    description: " A Headless CMS Blog.",
    image: "/images/19.png",
    tags: ["React", "Next", "Tailwind Css", "GraphQL"],
    source: "https://jahc.vercel.app/",
    visit: "https://github.com/Joshhortt/jc-blog-app",
    id: 14,
  },
  {
    title: "Creative Lightbox Blog",
    description: "A simple Blog.",
    image: "/images/20.png",
    tags: ["Html", "Css", "Svelte", "Javascript"],
    source: "https://creativelightbox.vercel.app/",
    visit: "https://github.com/Joshhortt/creativelightbox-blog",
    id: 15,
  },
  {
    title: "Hoje Aprendi",
    description: "A Full-stack app for students.",
    image: "/images/21.png",
    tags: ["React", "Javascript", "Supabase"],
    source: "https://hoje-aprendi.netlify.app/",
    visit: "https://github.com/Joshhortt/hojeaprendi",
    id: 16,
  },
  {
    title: "Rastrum",
    description: "Simple Note-Taking App.",
    image: "/images/22.png",
    tags: ["React", "Remix", "Javascript"],
    source: "https://rastrum.netlify.app/",
    visit: "https://github.com/Joshhortt/rastrum",
    id: 17,
  },
  {
    title: "Kadê Gastos",
    description: "A Full-Stack Spending Tracker Management App.",
    image: "/images/23.png",
    tags: ["React", "Remix", "MongoDB"],
    source: "https://kadegastos.netlify.app/",
    visit: "https://github.com/Joshhortt/kade-gastos",
    id: 18,
  },
  {
    title: "Project Prodigy",
    description: "Simple, powerful & flexible markdown-powered docs site.",
    image: "/images/24.png",
    tags: ["Javascript", "Typescript", "Next.js", "MDX"],
    source: "https://project-prodigy.vercel.app/",
    visit: "https://github.com/Joshhortt/project-prodigy",
    id: 19,
  },
  {
    title: "100devs",
    description: "A Blog for Web Development Students.",
    image: "/images/25.png",
    tags: ["Javascript", "React", "Next.js", "MDX"],
    source: "https://hundred-devs.vercel.app/",
    visit: "https://github.com/Joshhortt/hundred-devs",
    id: 20,
  },
  {
    title: "Solicitor",
    description: "A Solicitor Law Firm Blog Website.",
    image: "/images/26.png",
    tags: ["Javascript", "React", "Next.js", "MDX"],
    source: "https://evaristoamaro.pt/",
    staging: "https://evaristoamaro.vercel.app//",
    visit: "https://github.com/Joshhortt/solicitor",
    id: 21,
  },
  {
    title: "Digital Marketing Insights",
    description: "A Digital Marketing & E-commerce Documentation Website.",
    image: "/images/27.png",
    tags: ["TailwindCSS", "Astro", "MDX"],
    source: "https://digital-marketing-insights.vercel.app/",
    visit: "https://github.com/Joshhortt/digital-marketing-insights/",
    id: 22,
  },
];

export const TimeLineData = [
  { year: 2005, text: "Worked in IT Support & Help-desk" },
  { year: 2007, text: "Started my Freelance Web Developer journey" },
  { year: 2020, text: "Founded Creative Lightbox LLC" },
  { year: 2021, text: "Started my Technical Content writing journey" },
  { year: 2023, text: "I am officially an MBA graduate" },
  { year: 2023, text: "Graduated in Project management & Digital Marketing" },
];
