export const projects = [
  {
    title: 'Home & Home',
    description: "IN DEVELOPMENT. A Real Estate App showing rental homes and for-sale properties with advanced property filtering. Uses Rapid API and Chakra UI .",
    image: '/images/1.png',
    tags: ['React', 'Javascript', 'Next.js', 'Api'],
    source: 'https://google.com',
    visit: 'https://github.com/Joshhortt/home-home',
    id: 0,
  },
  {
    title: 'Expense Tracker App',
    description:"IN DEVELOPMENT. Voice Powered React App to track Income & Expenses. Uses Context API, Local Storage, Speechly, Material UI.",
    image: '/images/2.png',
    tags: ['React', 'Javascript', 'Api'],
    source: 'https://google.com',
    visit: 'https://github.com/Joshhortt/expense-tracker',
    id: 1,
  },
  {
    title: 'Cryptofast',
    description: "IN DEVELOPMENT. A React App using Redux Toolkit & Ant Design, creating charts, and fetching data from multiple sources using RapidAPI .",
      image: '/images/3.png',
      tags: ['React', 'Chart.js', 'Redux', 'Api'],
    source: 'https://google.com',
    visit: 'https://github.com/Joshhortt/crypto-fast',
    id: 2,
  },
  {
    title: 'Privatechat',
    description: "The Github code repository for the corresponding application. A Realtime Chat Application with Facebook and Google login.",
    image: '/images/4.png',
    tags: ['React', 'ChatEngine', 'Javascript', 'Firebase'],
    source: 'https://privatechatmessenger.netlify.app/',
    visit: 'https://github.com/Joshhortt/private-chat-messenger',
    id: 3,
  },
  {
    title: 'VPN Runners',
    description: "The Github code repository for the corresponding application. Virtual Private Network reviews Blog. Themify Wordpress Theme.",
    image: '/images/5.png',
    tags: ['Php', 'MySql', 'Javascript', 'Cms'],
    source: 'https://vpnrunners.com',
    staging: 'https://wordpress-607868-2283665.cloudwaysapps.com/',
    visit: 'https://github.com/Joshhortt/vpn-runners',
    id: 4,
  },
  {
    title: 'Creative Lightbox',
    description: "The Github code repository for the corresponding application. Personal Blog about E-business consulting. Twenty Twenty One Wordpress Theme.",
    image: '/images/6.png',
    tags: ['Php', 'MySql', 'Javascript', 'Cms'],
    source: 'https://creativelightbox.com',
    visit: 'https://github.com/Joshhortt/creative-lightbox',
    id: 5,
  },
  {
    title: 'CC Property Services',
    description: "The Github code repository for the corresponding application. Vacation Rental Property Services Company Landing Page. Astra Wordpress Theme.",
    image: '/images/7.png',
    tags: ['Php', 'MySql', 'Javascript', 'Cms'],
    source: 'https://casacasa.pt',
    visit: 'https://github.com/Joshhortt/casa-casa',
    id: 6,
  },
  {
  title: 'Bmatica',
  description: "The Github code repository for the corresponding application. Hardware & Software Development Company Landing Page. Divi Wordpress Theme",
  image: '/images/8.png',
  tags: ['Php', 'MySql', 'Javascript', 'Cms'],
  source: 'http://b-matica.com/',
  staging: 'http://wordpress-607868-1968877.cloudwaysapps.com/',
  visit: 'https://github.com/Joshhortt/b-matica',
  id: 7,
  },
  {
    title: 'Blue Door Lagos',
    description: "The Github code repository for the corresponding application. Vacation Rental Booking Website.  Sydney Wordpress Theme.",
    image: '/images/9.png',
    tags: ['Php', 'MySql','Javascript', 'Cms'],
    source: 'https://bluedoorlagos.com/',
    visit: 'https://github.com/Joshhortt/blue-door-lagos/',
    id: 8,
  },
  {
    title: 'Lagos Bay View Flat',
    description: "The Github code repository for the corresponding application. Vacation Rental Booking Website. Astra Wordpress Theme.",
    image: '/images/10.png',
    tags: ['Php', 'MySql', 'Javascript', 'Cms'],
    source: 'https://lagosbayviewflat.com/',
    visit: 'https://github.com/Joshhortt/lagos-bay-view-flat/',
    id: 9,
  },
  {
    title: 'Vinyl Flat',
    description: "The Github code repository for the corresponding application. Vacation Rental Booking Website. Sydney Wordpress Theme.",
    image: '/images/11.png',
    tags: ['Php', 'MySql', 'Javascript', 'Cms'],
    source: 'https://vinylflat.pt/',
    visit: 'https://github.com/Joshhortt/vinyl-flat/',
    id: 10,
  },
  {
  title: 'Casa Beatriz',
  description: "The Github code repository for the corresponding application. Vacation Rental Booking Website. Astra Wordpress Theme.",
  image: '/images/12.png',
  tags: ['Php', 'MySql', 'Javascript', 'Cms'],
  source: 'https://casabeatriz.pt/',
  visit: 'https://github.com/Joshhortt/casa-beatriz/',
  id: 11,
},
{
  title: 'Dev Match',
  description: "The Github code repository for the corresponding application. A Ruby on Rails CRUD Application.",
  image: '/images/13.png',
  tags: ['Ruby on Rails', 'MySql', 'Javascript'],
  source: 'https://lit-river-74323.herokuapp.com/',
  visit: 'https://github.com/Joshhortt/dev-match',
  id: 12,
},
{
  title: 'Designer Portfolio',
  description: "The Github code repository for the corresponding application. A simple Portfolio Landing Page.",
  image: '/images/14.png',
  tags: ['Html', 'Css', 'Javascript'],
  source: 'https://google.com/',
  visit: 'https://github.com/Joshhortt/designer-portfolio',
  id: 13,
},
];

export const TimeLineData = [
  { year: 2005, text: 'Worked in IT Support & Administration', },
  { year: 2017, text: 'Worked as a Wordpress Developer', },
  { year: 2019, text: 'Worked as a Systems Administrator', },
  { year: 2020, text: 'Started my Web Development journey', },
  { year: 2021, text: 'Founded Creative Lightbox.com', },
  // { year: 2022, text: 'Started my own online Business platform', },
];